import { AlertCircle, CheckCircle2, ChevronRight, Loader2, Mail, Package, Phone, ShieldCheck, Store, Truck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { trpc } from "@/lib/trpc";

const euro = (value: string | number) => new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" }).format(Number(value));

export default function ProspectSimulator() {
  const [quantities, setQuantities] = useState<Record<string, string>>({});
  const [contact, setContact] = useState({ legalName: "", contactName: "", email: "", phone: "", businessType: "", city: "", vatNumber: "", privacyAccepted: false, website: "" });
  const [submitted, setSubmitted] = useState<string | null>(null);
  const publicData = trpc.prospectSimulator.getPublicData.useQuery();
  const cartItems = useMemo(
    () => Object.entries(quantities)
      .map(([productId, rawQuantity]) => ({ productId, quantity: Number(rawQuantity) }))
      .filter((item) => Number.isInteger(item.quantity) && item.quantity > 0),
    [quantities],
  );
  const calculation = trpc.prospectSimulator.calculate.useQuery({ items: cartItems }, { enabled: cartItems.length > 0 });
  const submit = trpc.prospectSimulator.submit.useMutation({
    onSuccess: (result) => {
      setSubmitted(result.id);
      setQuantities({});
    },
  });

  const updateContact = (key: keyof typeof contact, value: string | boolean) => setContact((current) => ({ ...current, [key]: value }));
  const data = publicData.data;
  const result = calculation.data;

  if (publicData.isLoading) return <main className="min-h-screen bg-[#FAF7F0] grid place-items-center text-[#2D5A27]"><Loader2 className="h-7 w-7 animate-spin" /></main>;
  if (publicData.error || !data) return <main className="min-h-screen bg-[#FAF7F0] grid place-items-center p-6"><Card className="max-w-lg border-amber-200"><CardHeader><CardTitle className="flex items-center gap-2 text-[#2D5A27]"><AlertCircle className="text-[#F5A623]" />Simulatore non disponibile</CardTitle><CardDescription>{publicData.error?.message ?? "La configurazione commerciale non è ancora disponibile."}</CardDescription></CardHeader></Card></main>;

  const canSubmit = cartItems.length > 0 && contact.legalName && contact.contactName && contact.email && contact.phone && contact.businessType && contact.city && contact.vatNumber && contact.privacyAccepted;
  return <main className="min-h-screen bg-[#FAF7F0] text-[#254521]">
    <header className="border-b border-[#2D5A27]/10 bg-white/90 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><Link href="/simulatore-rivenditori" className="font-[Poppins] text-xl font-bold text-[#2D5A27]">SoKeto <span className="font-normal">per rivenditori</span></Link><span className="rounded-full bg-[#7AB648]/15 px-3 py-1 text-xs font-semibold text-[#2D5A27]">Simulazione riservata ai prospect</span></div>
    </header>
    <section className="border-b border-[#2D5A27]/10 bg-[#2D5A27] px-5 py-14 text-white"><div className="mx-auto max-w-7xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.16em] text-[#A9D57C]">Configura il tuo primo assortimento</p><h1 className="max-w-3xl font-[Poppins] text-4xl font-bold tracking-tight md:text-5xl">Costruisci il tuo ordine e scopri la fascia commerciale raggiunta.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/80">I prezzi per rivenditori sono indicati <strong>IVA esclusa</strong>. Il prezzo consigliato al pubblico è indicato <strong>IVA inclusa</strong>.</p></div></section>
    <div className="mx-auto grid max-w-7xl gap-7 px-5 py-8 lg:grid-cols-[minmax(0,1fr)_380px]">
      <section><div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="font-[Poppins] text-2xl font-bold text-[#2D5A27]">Catalogo per il tuo assortimento</h2><p className="mt-1 text-sm text-[#52634d]">Inserisci solo quantità intere maggiori di zero.</p></div><span className="text-sm text-[#52634d]">{data.products.length} prodotti disponibili</span></div>
        <div className="overflow-hidden rounded-xl border border-[#2D5A27]/10 bg-white shadow-sm"><div className="hidden grid-cols-[minmax(0,1fr)_120px_112px] gap-3 border-b border-[#2D5A27]/10 bg-[#F3F7ED] px-5 py-3 text-xs font-semibold uppercase tracking-wide text-[#52634d] md:grid"><span>Prodotto</span><span>Listino netto</span><span>Quantità</span></div>
          {data.products.map((product) => <div key={product.id} className="grid gap-3 border-b border-[#2D5A27]/10 px-5 py-4 last:border-0 md:grid-cols-[minmax(0,1fr)_120px_112px] md:items-center"><div><p className="font-medium text-[#254521]">{product.name}</p><p className="mt-0.5 text-xs text-[#6B7C66]">{product.sku} · IVA {Number(product.vatRate).toFixed(0)}% · {product.piecesPerUnit} {product.unitLabel}</p></div><p className="font-semibold text-[#2D5A27]">{euro(product.unitListNet)}<span className="block text-[11px] font-normal text-[#6B7C66]">IVA esclusa</span></p><Input aria-label={`Quantità ${product.name}`} type="number" min="0" step="1" value={quantities[product.id] ?? ""} onChange={(event) => setQuantities((current) => ({ ...current, [product.id]: event.target.value }))} className="border-[#2D5A27]/20" placeholder="0" /></div>)}
        </div>
        {result && <section className="mt-7"><div className="mb-4"><h2 className="font-[Poppins] text-xl font-bold text-[#2D5A27]">Prezzi del tuo assortimento</h2><p className="mt-1 text-sm text-[#52634d]">I prezzi per fascia sono unitari e <strong>IVA esclusa</strong>. Il consigliato è il prezzo a scaffale, <strong>IVA inclusa</strong>.</p></div><div className="overflow-x-auto rounded-xl border border-[#2D5A27]/10 bg-white shadow-sm"><table className="w-full min-w-[920px] text-sm"><thead className="bg-[#F3F7ED] text-left text-xs uppercase tracking-wide text-[#52634d]"><tr><th className="px-4 py-3">Prodotto</th><th className="px-3 py-3">Q.tà</th><th className="px-3 py-3">Listino netto</th><th className="px-3 py-3">Consigliato lordo</th>{result.tiers.map((tier) => <th key={tier.code} className="px-3 py-3">{tier.name}<span className="block normal-case tracking-normal">-{Number(tier.discount_percent).toFixed(2)}%</span></th>)}</tr></thead><tbody>{result.items.map((item) => <tr key={item.id} className="border-t border-[#2D5A27]/10"><td className="px-4 py-3 font-medium text-[#254521]">{item.name}<span className="block text-xs font-normal text-[#6B7C66]">{item.sku} · IVA {Number(item.vatRate).toFixed(0)}%</span></td><td className="px-3 py-3">{item.quantity}</td><td className="px-3 py-3">{euro(item.unitListNet)}<span className="block text-[11px] text-[#6B7C66]">IVA escl.</span></td><td className="px-3 py-3 font-semibold text-[#2D5A27]">{euro(item.recommendedPublicGross)}<span className="block text-[11px] font-normal text-[#6B7C66]">IVA incl.</span></td>{item.tierPrices.map((price) => <td key={price.tierCode} className="px-3 py-3"><strong>{euro(price.unitNet)}</strong><span className="block text-[11px] text-[#6B7C66]">IVA escl.</span></td>)}</tr>)}</tbody></table></div></section>}
      </section>
      <aside className="space-y-5 lg:sticky lg:top-5 lg:self-start">
        <Card className="overflow-hidden border-[#2D5A27]/15 shadow-md"><CardHeader className="bg-[#2D5A27] text-white"><CardTitle className="font-[Poppins]">La tua simulazione</CardTitle><CardDescription className="text-white/70">Basata sul listino netto selezionato.</CardDescription></CardHeader><CardContent className="space-y-5 p-5">{calculation.isFetching ? <div className="flex items-center gap-2 text-sm text-[#52634d]"><Loader2 className="h-4 w-4 animate-spin" />Calcolo in corso…</div> : result ? <><div><p className="text-sm text-[#52634d]">Totale a listino</p><p className="font-[Poppins] text-3xl font-bold text-[#2D5A27]">{euro(result.listSubtotalNet)}</p><p className="text-xs text-[#6B7C66]">IVA esclusa</p></div><div className="rounded-lg border border-[#7AB648]/35 bg-[#7AB648]/10 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[#426b2f]">Fascia raggiunta</p><p className="mt-1 text-xl font-bold text-[#2D5A27]">{result.reachedTier.name}</p><p className="mt-1 text-sm text-[#426b2f]">Sconto {Number(result.reachedTier.discount_percent).toFixed(2)}%</p>{result.nextTier && <p className="mt-3 border-t border-[#7AB648]/30 pt-3 text-sm text-[#52634d]">Mancano <strong>{euro(result.nextTier.additionalListNet)}</strong> di listino per {result.nextTier.name}.</p>}</div><div className="space-y-3">{result.tiers.map((tier) => <div key={tier.code} className={`rounded-lg border p-3 ${tier.code === result.reachedTier.code ? "border-[#7AB648] bg-[#F3F7ED]" : "border-[#2D5A27]/10"}`}><div className="flex justify-between gap-2"><p className="font-semibold text-[#2D5A27]">{tier.name}</p><p className="text-sm font-semibold">{Number(tier.discount_percent).toFixed(2)}%</p></div><p className="mt-1 text-sm text-[#52634d]">Prezzo merce: {euro(tier.merchandiseNet)} <span className="text-xs">IVA esclusa</span></p><p className="mt-0.5 text-sm text-[#52634d]">Margine lordo potenziale: <strong>{euro(tier.potentialMarginNet)} · {tier.potentialMarginPercent}%</strong></p></div>)}</div><div className="space-y-2 border-t border-[#2D5A27]/10 pt-4 text-sm text-[#52634d]"><p className="flex gap-2"><Truck className="mt-0.5 h-4 w-4 shrink-0 text-[#7AB648]" />Spedizione {result.freeShippingApplied ? <strong>gratuita</strong> : <><strong>{euro(result.shippingNet)}</strong> IVA esclusa</>}</p><p className="flex gap-2"><Package className="mt-0.5 h-4 w-4 shrink-0 text-[#7AB648]" />{result.displayStandUnlocked ? <strong>Espositore in omaggio incluso.</strong> : <>Espositore in omaggio sopra {euro(result.displayStandThreshold)} di listino netto.</>}</p><p>Minimo ordine: <strong>{euro(result.minimumOrderNet)}</strong> IVA esclusa {result.meetsMinimumOrder ? <span className="text-[#426b2f]">— raggiunto</span> : <span className="text-[#B45B00]">— non raggiunto</span>}.</p></div></> : <p className="text-sm leading-6 text-[#52634d]">Aggiungi un prodotto per vedere prezzi, fasce e margini potenziali.</p>}</CardContent></Card>
        {result && <Card className="border-[#2D5A27]/15"><CardHeader><CardTitle className="font-[Poppins] text-lg text-[#2D5A27]">Richiedi un contatto</CardTitle><CardDescription>Salveremo questa simulazione per preparare la proposta commerciale.</CardDescription></CardHeader><CardContent>{submitted ? <div className="rounded-lg bg-[#7AB648]/10 p-4 text-sm text-[#254521]"><CheckCircle2 className="mb-2 h-5 w-5 text-[#426b2f]" /><strong>Richiesta ricevuta.</strong><p className="mt-1">Ti ricontatteremo ai recapiti indicati.</p></div> : <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); if (canSubmit) submit.mutate({ ...contact, privacyAccepted: true, items: cartItems }); }}><div className="hidden" aria-hidden="true"><Label htmlFor="website">Sito web</Label><Input id="website" tabIndex={-1} autoComplete="off" value={contact.website} onChange={(event) => updateContact("website", event.target.value)} /></div><Input required placeholder="Ragione sociale" value={contact.legalName} onChange={(event) => updateContact("legalName", event.target.value)} /><Input required placeholder="Nome e cognome referente" value={contact.contactName} onChange={(event) => updateContact("contactName", event.target.value)} /><Input required type="email" placeholder="Email" value={contact.email} onChange={(event) => updateContact("email", event.target.value)} /><Input required placeholder="Telefono" value={contact.phone} onChange={(event) => updateContact("phone", event.target.value)} /><Input required placeholder="Tipo di attività" value={contact.businessType} onChange={(event) => updateContact("businessType", event.target.value)} /><div className="grid grid-cols-2 gap-3"><Input required placeholder="Città" value={contact.city} onChange={(event) => updateContact("city", event.target.value)} /><Input required placeholder="P. IVA" value={contact.vatNumber} onChange={(event) => updateContact("vatNumber", event.target.value)} /></div><label className="flex cursor-pointer items-start gap-2 pt-1 text-xs leading-5 text-[#52634d]"><Checkbox checked={contact.privacyAccepted} onCheckedChange={(value) => updateContact("privacyAccepted", value === true)} /><span>Ho letto l’<a className="font-semibold text-[#2D5A27] underline" href={data.config.privacyPolicyUrl} target="_blank" rel="noreferrer">informativa privacy</a> e acconsento al trattamento dei dati per ricevere un contatto commerciale.</span></label>{submit.error && <p className="text-sm text-destructive">{submit.error.message}</p>}<Button type="submit" disabled={!canSubmit || submit.isPending} className="w-full bg-[#2D5A27] hover:bg-[#254521]">{submit.isPending ? <Loader2 className="animate-spin" /> : <><Mail />Invia richiesta <ChevronRight /></>}</Button></form>}</CardContent></Card>}
      </aside>
    </div>
    <footer className="border-t border-[#2D5A27]/10 px-5 py-7 text-center text-xs text-[#6B7C66]"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />Le simulazioni hanno finalità informativa e commerciale. Il margine è calcolato su valori netti e rappresenta un margine lordo potenziale, prima dei costi del punto vendita.</footer>
  </main>;
}
